- gmime version check with autotools - gmime version workarounds

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -902,10 +902,13 @@ glib_CFLAGS
 glib_LIBS
 pcre_CFLAGS
 pcre_LIBS
+gmime24_CFLAGS
+gmime24_LIBS
 gmime_CFLAGS
 gmime_LIBS
 esmtpconfig
 SPMFILTER_QUEUE_DIR
+GMIME_VERSION
 LIBDIR
 LIBOBJS
 LTLIBOBJS'
@@ -942,6 +945,8 @@ glib_CFLAGS
 glib_LIBS
 pcre_CFLAGS
 pcre_LIBS
+gmime24_CFLAGS
+gmime24_LIBS
 gmime_CFLAGS
 gmime_LIBS'
 
@@ -1610,6 +1615,10 @@ Some influential environment variables:
   glib_LIBS   linker flags for glib, overriding pkg-config
   pcre_CFLAGS C compiler flags for pcre, overriding pkg-config
   pcre_LIBS   linker flags for pcre, overriding pkg-config
+  gmime24_CFLAGS
+              C compiler flags for gmime24, overriding pkg-config
+  gmime24_LIBS
+              linker flags for gmime24, overriding pkg-config
   gmime_CFLAGS
               C compiler flags for gmime, overriding pkg-config
   gmime_LIBS  linker flags for gmime, overriding pkg-config
@@ -4444,7 +4453,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4447 "configure"' > conftest.$ac_ext
+  echo '#line 4456 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7551,11 +7560,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7554: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7563: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7558: \$? = $ac_status" >&5
+   echo "$as_me:7567: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7841,11 +7850,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7844: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7853: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7848: \$? = $ac_status" >&5
+   echo "$as_me:7857: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7945,11 +7954,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7948: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7957: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:7952: \$? = $ac_status" >&5
+   echo "$as_me:7961: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10345,7 +10354,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10348 "configure"
+#line 10357 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10445,7 +10454,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10448 "configure"
+#line 10457 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12854,11 +12863,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12857: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12866: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12861: \$? = $ac_status" >&5
+   echo "$as_me:12870: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -12958,11 +12967,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12961: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12970: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12965: \$? = $ac_status" >&5
+   echo "$as_me:12974: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14541,11 +14550,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14544: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14553: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14548: \$? = $ac_status" >&5
+   echo "$as_me:14557: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14645,11 +14654,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14648: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14657: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14652: \$? = $ac_status" >&5
+   echo "$as_me:14661: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16860,11 +16869,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16863: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16872: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16867: \$? = $ac_status" >&5
+   echo "$as_me:16876: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17150,11 +17159,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17153: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17162: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17157: \$? = $ac_status" >&5
+   echo "$as_me:17166: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17254,11 +17263,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17257: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17266: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:17261: \$? = $ac_status" >&5
+   echo "$as_me:17270: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -20292,6 +20301,66 @@ fi
 	fi
 
 
+
+
+pkg_failed=no
+{ $as_echo "$as_me:$LINENO: checking for gmime24" >&5
+$as_echo_n "checking for gmime24... " >&6; }
+
+if test -n "$gmime24_CFLAGS"; then
+    pkg_cv_gmime24_CFLAGS="$gmime24_CFLAGS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"gmime-2.4 >= 2.4\"") >&5
+  ($PKG_CONFIG --exists --print-errors "gmime-2.4 >= 2.4") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_gmime24_CFLAGS=`$PKG_CONFIG --cflags "gmime-2.4 >= 2.4" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+if test -n "$gmime24_LIBS"; then
+    pkg_cv_gmime24_LIBS="$gmime24_LIBS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"gmime-2.4 >= 2.4\"") >&5
+  ($PKG_CONFIG --exists --print-errors "gmime-2.4 >= 2.4") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_gmime24_LIBS=`$PKG_CONFIG --libs "gmime-2.4 >= 2.4" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        gmime24_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors "gmime-2.4 >= 2.4" 2>&1`
+        else
+	        gmime24_PKG_ERRORS=`$PKG_CONFIG --print-errors "gmime-2.4 >= 2.4" 2>&1`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$gmime24_PKG_ERRORS" >&5
+
+	{ $as_echo "$as_me:$LINENO: result: no" >&5
+$as_echo "no" >&6; }
+
+
 pkg_failed=no
 { $as_echo "$as_me:$LINENO: checking for gmime" >&5
 $as_echo_n "checking for gmime... " >&6; }
@@ -20398,8 +20467,138 @@ else
 $as_echo "yes" >&6; }
 	:
 fi
-CFLAGS="$CFLAGS $gmime_CFLAGS"
-LDFLAGS="$LDFLAGS $gmime_LIBS"
+		CFLAGS="$CFLAGS $gmime_CFLAGS"
+		LDFLAGS="$LDFLAGS $gmime_LIBS"
+		modver=`$PKG_CONFIG --modversion gmime-2.0`
+
+elif test $pkg_failed = untried; then
+
+
+pkg_failed=no
+{ $as_echo "$as_me:$LINENO: checking for gmime" >&5
+$as_echo_n "checking for gmime... " >&6; }
+
+if test -n "$gmime_CFLAGS"; then
+    pkg_cv_gmime_CFLAGS="$gmime_CFLAGS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"gmime-2.0 >= 2.0\"") >&5
+  ($PKG_CONFIG --exists --print-errors "gmime-2.0 >= 2.0") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_gmime_CFLAGS=`$PKG_CONFIG --cflags "gmime-2.0 >= 2.0" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+if test -n "$gmime_LIBS"; then
+    pkg_cv_gmime_LIBS="$gmime_LIBS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"gmime-2.0 >= 2.0\"") >&5
+  ($PKG_CONFIG --exists --print-errors "gmime-2.0 >= 2.0") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_gmime_LIBS=`$PKG_CONFIG --libs "gmime-2.0 >= 2.0" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        gmime_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors "gmime-2.0 >= 2.0" 2>&1`
+        else
+	        gmime_PKG_ERRORS=`$PKG_CONFIG --print-errors "gmime-2.0 >= 2.0" 2>&1`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$gmime_PKG_ERRORS" >&5
+
+	{ { $as_echo "$as_me:$LINENO: error: Package requirements (gmime-2.0 >= 2.0) were not met:
+
+$gmime_PKG_ERRORS
+
+Consider adjusting the PKG_CONFIG_PATH environment variable if you
+installed software in a non-standard prefix.
+
+Alternatively, you may set the environment variables gmime_CFLAGS
+and gmime_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&5
+$as_echo "$as_me: error: Package requirements (gmime-2.0 >= 2.0) were not met:
+
+$gmime_PKG_ERRORS
+
+Consider adjusting the PKG_CONFIG_PATH environment variable if you
+installed software in a non-standard prefix.
+
+Alternatively, you may set the environment variables gmime_CFLAGS
+and gmime_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&2;}
+   { (exit 1); exit 1; }; }
+elif test $pkg_failed = untried; then
+	{ { $as_echo "$as_me:$LINENO: error: The pkg-config script could not be found or is too old.  Make sure it
+is in your PATH or set the PKG_CONFIG environment variable to the full
+path to pkg-config.
+
+Alternatively, you may set the environment variables gmime_CFLAGS
+and gmime_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+
+To get pkg-config, see <http://pkg-config.freedesktop.org/>.
+See \`config.log' for more details." >&5
+$as_echo "$as_me: error: The pkg-config script could not be found or is too old.  Make sure it
+is in your PATH or set the PKG_CONFIG environment variable to the full
+path to pkg-config.
+
+Alternatively, you may set the environment variables gmime_CFLAGS
+and gmime_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+
+To get pkg-config, see <http://pkg-config.freedesktop.org/>.
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }
+else
+	gmime_CFLAGS=$pkg_cv_gmime_CFLAGS
+	gmime_LIBS=$pkg_cv_gmime_LIBS
+        { $as_echo "$as_me:$LINENO: result: yes" >&5
+$as_echo "yes" >&6; }
+	:
+fi
+		CFLAGS="$CFLAGS $gmime_CFLAGS"
+		LDFLAGS="$LDFLAGS $gmime_LIBS"
+		modver=`$PKG_CONFIG --modversion gmime-2.0`
+
+else
+	gmime24_CFLAGS=$pkg_cv_gmime24_CFLAGS
+	gmime24_LIBS=$pkg_cv_gmime24_LIBS
+        { $as_echo "$as_me:$LINENO: result: yes" >&5
+$as_echo "yes" >&6; }
+
+		CFLAGS="$CFLAGS $gmime24_CFLAGS"
+		LDFLAGS="$LDFLAGS $gmime24_LIBS"
+		modver=`$PKG_CONFIG --modversion gmime-2.4`
+
+fi
+	gmime_major=`echo $modver | sed 's/\([0-9]*\).\([0-9]*\).\([0-9]*\)/\1/'`
+	gmime_minor=`echo $modver | sed 's/\([0-9]*\).\([0-9]*\).\([0-9]*\)/\2/'`
+	gmime_micro=`echo $modver | sed 's/\([0-9]*\).\([0-9]*\).\([0-9]*\)/\3/'`
+	GMIME_VERSION=`echo $gmime_major*10000+$gmime_minor*100+$gmime_micro|bc`
 
 
 # Extract the first word of "libesmtp-config", so it can be a program name with args.
@@ -20505,6 +20704,7 @@ then
 else
 	pkglibdir=`eval echo /usr/local/lib/${PACKAGE}`
 fi
+
 
 
 
